spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/messagingapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET:7132CE6EF35F2E76CBF9CBBAAF4F5XX}

