plugins {
    id 'java'
    id 'checkstyle'
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.4'
}


group = 'com.example'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.mindrot:jbcrypt:0.4'
    runtimeOnly 'org.postgresql:postgresql'
}

checkstyle {
    toolVersion = '10.21.4'
    config = resources.text.fromArchiveEntry(configurations.checkstyle.first(), 'google_checks.xml')
    showViolations = true
    ignoreFailures = false
}

build.dependsOn checkstyleMain, checkstyleTest

test {
    useJUnitPlatform()
}