services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: messagingapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    image: xavbe/messaging-backend:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/messagingapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  frontend:
    image: xavbe/messaging-frontend:1.0
    ports:
      - "5173:80"
    depends_on:
      - backend