spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/messagingapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

jwt.secret=${JWT_SECRET:7132CE6EF35F2E76CBF9CBBAAF4F5FF2}
app.cookie.secure=${APP_COOKIE_SECURE:false}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:DEBUG}
